server:
  port: 8083
  servlet:
    context-path: /api

cumulativeStats:
  playersByCategory: "https://api.mysportsfeeds.com/v1.2/pull/nba/2018-2019-regular/cumulative_player_stats.json?sort={category}&limit={limit}"
    # the stat to sort by and the limit will be passed in via the FE since FE will request for more than 10 behind the scenes after initial call

application:
  authorization: "6d198567-ca61-4221-8838-084b06:Lakers23"
